package ufes.br.sistemadesupermercadomvp.mvp.view;

/**
 *
 * @author João Vitor
 */
public class CategoriaProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form CategoriaProdutoView
     */
    public CategoriaProdutoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpCategoriaProduto = new javax.swing.JDesktopPane();
        dpCategoria = new javax.swing.JDesktopPane();
        lblCategoria = new javax.swing.JLabel();
        lblPercentual = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtPercentual = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        dpCategoriasCadastradas = new javax.swing.JDesktopPane();
        scrlCategoria = new javax.swing.JScrollPane();
        tbCategoria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Categoria de Produtos");

        dpCategoriaProduto.setBackground(new java.awt.Color(255, 255, 255));

        dpCategoria.setBackground(new java.awt.Color(234, 234, 234));
        dpCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(null), "Modo: Visualização"), "Detalhes da Categoria"));

        lblCategoria.setText("Categoria:");

        lblPercentual.setText("Percentual de Lucro (%):");

        btnNovo.setText("Novo");

        btnEditar.setText("Editar");

        btnExcluir.setText("Excluir");

        btnSalvar.setText("Salvar");

        btnCancelar.setText("Cancelar");

        btnFechar.setText("Fechar");

        dpCategoria.setLayer(lblCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(lblPercentual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(txtCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(txtPercentual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(btnNovo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(btnExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(btnSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoria.setLayer(btnFechar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpCategoriaLayout = new javax.swing.GroupLayout(dpCategoria);
        dpCategoria.setLayout(dpCategoriaLayout);
        dpCategoriaLayout.setHorizontalGroup(
            dpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpCategoriaLayout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpCategoriaLayout.createSequentialGroup()
                        .addGroup(dpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPercentual)
                            .addComponent(lblCategoria))
                        .addGap(18, 18, 18)
                        .addGroup(dpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dpCategoriaLayout.setVerticalGroup(
            dpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpCategoriaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercentual)
                    .addComponent(txtPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dpCategoriasCadastradas.setBackground(new java.awt.Color(234, 234, 234));
        dpCategoriasCadastradas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Categorias Cadastradas"));

        tbCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Percentual de Lucro (%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrlCategoria.setViewportView(tbCategoria);

        dpCategoriasCadastradas.setLayer(scrlCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpCategoriasCadastradasLayout = new javax.swing.GroupLayout(dpCategoriasCadastradas);
        dpCategoriasCadastradas.setLayout(dpCategoriasCadastradasLayout);
        dpCategoriasCadastradasLayout.setHorizontalGroup(
            dpCategoriasCadastradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpCategoriasCadastradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlCategoria)
                .addContainerGap())
        );
        dpCategoriasCadastradasLayout.setVerticalGroup(
            dpCategoriasCadastradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpCategoriasCadastradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        dpCategoriaProduto.setLayer(dpCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpCategoriaProduto.setLayer(dpCategoriasCadastradas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpCategoriaProdutoLayout = new javax.swing.GroupLayout(dpCategoriaProduto);
        dpCategoriaProduto.setLayout(dpCategoriaProdutoLayout);
        dpCategoriaProdutoLayout.setHorizontalGroup(
            dpCategoriaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpCategoriaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dpCategoriaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dpCategoria)
                    .addComponent(dpCategoriasCadastradas))
                .addContainerGap())
        );
        dpCategoriaProdutoLayout.setVerticalGroup(
            dpCategoriaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpCategoriaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dpCategoriasCadastradas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpCategoriaProduto)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpCategoriaProduto)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoriaProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JDesktopPane dpCategoria;
    private javax.swing.JDesktopPane dpCategoriaProduto;
    private javax.swing.JDesktopPane dpCategoriasCadastradas;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblPercentual;
    private javax.swing.JScrollPane scrlCategoria;
    private javax.swing.JTable tbCategoria;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtPercentual;
    // End of variables declaration//GEN-END:variables
}
