package ufes.br.sistemadesupermercadomvp.mvp.view;

/**
 *
 * @author João Vitor
 */
public class BuscarProdutosView extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProdutosView
     */
    public BuscarProdutosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPainelPrincipal = new javax.swing.JDesktopPane();
        camadaBuscar = new javax.swing.JLayeredPane();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cbBuscar = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        scrlPainel = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        separador = new javax.swing.JSeparator();
        btnNovo = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnVizualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Produtos");
        setBackground(new java.awt.Color(105, 152, 181));

        dpPainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        camadaBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar"));

        lblBuscar.setText("Buscar por:");
        lblBuscar.setToolTipText("");

        cbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome do Produto", "Valor do Produto", "Categoria do Produto" }));

        btnBuscar.setText("Buscar");

        camadaBuscar.setLayer(lblBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        camadaBuscar.setLayer(txtBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        camadaBuscar.setLayer(cbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        camadaBuscar.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout camadaBuscarLayout = new javax.swing.GroupLayout(camadaBuscar);
        camadaBuscar.setLayout(camadaBuscarLayout);
        camadaBuscarLayout.setHorizontalGroup(
            camadaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camadaBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(camadaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscar)
                    .addGroup(camadaBuscarLayout.createSequentialGroup()
                        .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        camadaBuscarLayout.setVerticalGroup(
            camadaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camadaBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(camadaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Produto", "Preço de Custo ", "Categoria", "Margem de Lucro (%)", "Preço de Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProdutos.setShowGrid(false);
        scrlPainel.setViewportView(tblProdutos);

        btnNovo.setText("Novo");

        btnFechar.setText("Fechar");

        btnVizualizar.setText("Visualizar");

        dpPainelPrincipal.setLayer(camadaBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPainelPrincipal.setLayer(scrlPainel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPainelPrincipal.setLayer(separador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPainelPrincipal.setLayer(btnNovo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPainelPrincipal.setLayer(btnFechar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPainelPrincipal.setLayer(btnVizualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpPainelPrincipalLayout = new javax.swing.GroupLayout(dpPainelPrincipal);
        dpPainelPrincipal.setLayout(dpPainelPrincipalLayout);
        dpPainelPrincipalLayout.setHorizontalGroup(
            dpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador)
                    .addComponent(camadaBuscar)
                    .addComponent(scrlPainel)
                    .addGroup(dpPainelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVizualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dpPainelPrincipalLayout.setVerticalGroup(
            dpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(camadaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnFechar)
                    .addComponent(btnVizualizar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpPainelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpPainelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProdutosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVizualizar;
    private javax.swing.JLayeredPane camadaBuscar;
    private javax.swing.JComboBox<String> cbBuscar;
    private javax.swing.JDesktopPane dpPainelPrincipal;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JScrollPane scrlPainel;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
