package ufes.br.sistemadesupermercadomvp.mvp.view;

/**
 *
 * @author João Vitor
 */
public class HistoricoPrecoView extends javax.swing.JFrame {

    /**
     * Creates new form HistoricoPrecoView
     */
    public HistoricoPrecoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpHistorico = new javax.swing.JDesktopPane();
        separador1 = new javax.swing.JSeparator();
        lblProduto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();
        scrlHistorico = new javax.swing.JScrollPane();
        tblHistorico = new javax.swing.JTable();
        separador3 = new javax.swing.JSeparator();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Histórico de Preços do Produto");

        dpHistorico.setBackground(new java.awt.Color(255, 255, 255));

        lblProduto.setText("Produto:");

        lblCategoria.setText("Categoria:");

        txtProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tblHistorico.setAutoCreateRowSorter(true);
        tblHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "Percentual de Lucro (%)", "Preço de Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrlHistorico.setViewportView(tblHistorico);

        btnFechar.setBackground(new java.awt.Color(204, 204, 204));
        btnFechar.setText("Fechar");

        dpHistorico.setLayer(separador1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpHistorico.setLayer(lblProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpHistorico.setLayer(lblCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpHistorico.setLayer(txtProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpHistorico.setLayer(txtCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpHistorico.setLayer(separador2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpHistorico.setLayer(scrlHistorico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpHistorico.setLayer(separador3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpHistorico.setLayer(btnFechar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpHistoricoLayout = new javax.swing.GroupLayout(dpHistorico);
        dpHistorico.setLayout(dpHistoricoLayout);
        dpHistoricoLayout.setHorizontalGroup(
            dpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpHistoricoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(dpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProduto)
                            .addComponent(lblCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                            .addComponent(txtCategoria))
                        .addGap(33, 33, 33))
                    .addGroup(dpHistoricoLayout.createSequentialGroup()
                        .addGroup(dpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separador2)
                            .addComponent(separador1)
                            .addComponent(scrlHistorico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separador3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(dpHistoricoLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 305, Short.MAX_VALUE))
        );
        dpHistoricoLayout.setVerticalGroup(
            dpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpHistorico)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpHistorico)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoPrecoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoPrecoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoPrecoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoPrecoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoPrecoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JDesktopPane dpHistorico;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JScrollPane scrlHistorico;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JTable tblHistorico;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
