package ufes.br.sistemadesupermercado.mvp.view;

import javax.swing.*;

/**
 *
 * @author ludico
 */
public class CalculoMargemLucroView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculoMargemLucroView.class.getName());

    /**
     * Creates new form CalculoMargemLucroView
     */
    public CalculoMargemLucroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        dpFiltro = new javax.swing.JDesktopPane();
        lblData = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        cbTipoCalculo = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        dpTabela = new javax.swing.JDesktopPane();
        scrlProduto = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculo de Margem de Lucro");

        dpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        dpFiltro.setBackground(new java.awt.Color(240, 240, 240));
        dpFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Filtros"));

        lblData.setText("Data do Cálculo:");

        lblMensagem.setText("O cálculo só pode ser realizado novamente após 10 dias.");

        cbTipoCalculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Nome do Produto" }));

        btnCalcular.setText("Calcular");

        dpFiltro.setLayer(lblData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpFiltro.setLayer(lblMensagem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpFiltro.setLayer(cbTipoCalculo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpFiltro.setLayer(btnCalcular, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpFiltroLayout = new javax.swing.GroupLayout(dpFiltro);
        dpFiltro.setLayout(dpFiltroLayout);
        dpFiltroLayout.setHorizontalGroup(
            dpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpFiltroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem)
                    .addGroup(dpFiltroLayout.createSequentialGroup()
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular)))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        dpFiltroLayout.setVerticalGroup(
            dpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpFiltroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(dpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular)
                    .addComponent(lblData))
                .addGap(18, 18, 18)
                .addComponent(lblMensagem)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        dpTabela.setBackground(new java.awt.Color(243, 233, 233));

        tbProduto.setAutoCreateRowSorter(true);
        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome do Produto", "Preço Unitário", "Categoria", "Percentual de Lucro", "Preco de Venda Calculado"
            }
        ));
        scrlProduto.setViewportView(tbProduto);

        dpTabela.setLayer(scrlProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpTabelaLayout = new javax.swing.GroupLayout(dpTabela);
        dpTabela.setLayout(dpTabelaLayout);
        dpTabelaLayout.setHorizontalGroup(
            dpTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );
        dpTabelaLayout.setVerticalGroup(
            dpTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnFechar.setBackground(new java.awt.Color(204, 204, 204));
        btnFechar.setText("Fechar");

        dpPrincipal.setLayer(dpFiltro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPrincipal.setLayer(dpTabela, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPrincipal.setLayer(btnFechar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpPrincipalLayout = new javax.swing.GroupLayout(dpPrincipal);
        dpPrincipal.setLayout(dpPrincipalLayout);
        dpPrincipalLayout.setHorizontalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dpFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dpTabela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dpPrincipalLayout.setVerticalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dpFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnFechar;
    private javax.swing.JComboBox<String> cbTipoCalculo;
    private javax.swing.JDesktopPane dpFiltro;
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JDesktopPane dpTabela;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JScrollPane scrlProduto;
    private javax.swing.JTable tbProduto;
    // End of variables declaration//GEN-END:variables


    public JButton getBtnCalcular() {
        return btnCalcular;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JComboBox<String> getCbTipoCalculo() {
        return cbTipoCalculo;
    }

    public JDesktopPane getDpFiltro() {
        return dpFiltro;
    }

    public JDesktopPane getDpPrincipal() {
        return dpPrincipal;
    }

    public JDesktopPane getDpTabela() {
        return dpTabela;
    }

    public JLabel getLblData() {
        return lblData;
    }

    public JLabel getLblMensagem() {
        return lblMensagem;
    }

    public JScrollPane getScrlProduto() {
        return scrlProduto;
    }

    public JTable getTbProduto() {
        return tbProduto;
    }
}
