package ufes.br.sistemadesupermercado.mvp.view;

import javax.swing.*;

/**
 *
 * @author João Vitor
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JMenuBar();
        menuDados = new javax.swing.JMenu();
        menuItemIncluirDados = new javax.swing.JMenuItem();
        menuItemBuscarProdutos = new javax.swing.JMenuItem();
        menuItemCategoria = new javax.swing.JMenuItem();
        menuItemCalcularMargemDeLucro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Supermercado");

        menuDados.setText("Dados");

        menuItemIncluirDados.setText("Incluir Dados");
        menuDados.add(menuItemIncluirDados);

        menuItemBuscarProdutos.setText("Buscar Produtos");
        menuDados.add(menuItemBuscarProdutos);

        menuItemCategoria.setText("Categorias");
        menuDados.add(menuItemCategoria);

        menuItemCalcularMargemDeLucro.setText("Calcular Margem de Lucro");
        menuDados.add(menuItemCalcularMargemDeLucro);

        menuPrincipal.add(menuDados);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuDados;
    private javax.swing.JMenuItem menuItemBuscarProdutos;
    private javax.swing.JMenuItem menuItemCalcularMargemDeLucro;
    private javax.swing.JMenuItem menuItemCategoria;
    private javax.swing.JMenuItem menuItemIncluirDados;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables


    public JMenu getMenuDados() {
        return menuDados;
    }

    public JMenuItem getMenuItemBuscarProdutos() {
        return menuItemBuscarProdutos;
    }

    public JMenuItem getMenuItemCalcularMargemDeLucro() {
        return menuItemCalcularMargemDeLucro;
    }

    public JMenuItem getMenuItemCategoria() {
        return menuItemCategoria;
    }

    public JMenuItem getMenuItemIncluirDados() {
        return menuItemIncluirDados;
    }

    public JMenuBar getMenuPrincipal() {
        return menuPrincipal;
    }
}
