package ufes.br.sistemadesupermercado.mvp.view;

import javax.swing.*;

/**
 *
 * @author João Vitor
 */
public class VisualizacaoProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form InclusaoEdicaoProdutosView
     */
    public VisualizacaoProdutoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        dpDadosProduto = new javax.swing.JDesktopPane();
        lblNomeProduto = new javax.swing.JLabel();
        lblPrecoCusto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblMargem = new javax.swing.JLabel();
        lblPrecoVenda = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        txtNomeProduto = new javax.swing.JTextField();
        txtPrecoCusto = new javax.swing.JTextField();
        txtMargem = new javax.swing.JTextField();
        txtPrecoVenda = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produto - Visualização");
        setBackground(new java.awt.Color(122, 196, 220));

        dpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        dpDadosProduto.setBackground(new java.awt.Color(238, 241, 241));
        dpDadosProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)), "Dados do Produto"));

        lblNomeProduto.setText("Nome do Produto:");

        lblPrecoCusto.setText("Preço de Custo:");

        lblCategoria.setText("Categoria do Produto:");

        lblMargem.setText("Margem de Lucro (%):");

        lblPrecoVenda.setText("Preço de Venda:");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Educação", "Papelaria", "Alimentação", "Lazer", "Entretenimento", "Higiene", "Limpeza" }));

        dpDadosProduto.setLayer(lblNomeProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(lblPrecoCusto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(lblCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(lblMargem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(lblPrecoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(cbCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(txtNomeProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(txtPrecoCusto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(txtMargem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpDadosProduto.setLayer(txtPrecoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpDadosProdutoLayout = new javax.swing.GroupLayout(dpDadosProduto);
        dpDadosProduto.setLayout(dpDadosProdutoLayout);
        dpDadosProdutoLayout.setHorizontalGroup(
            dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpDadosProdutoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeProduto)
                    .addComponent(lblPrecoCusto)
                    .addComponent(lblCategoria)
                    .addComponent(lblMargem)
                    .addComponent(lblPrecoVenda))
                .addGap(48, 48, 48)
                .addGroup(dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpDadosProdutoLayout.createSequentialGroup()
                        .addGroup(dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtPrecoCusto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMargem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbCategoria, 0, 478, Short.MAX_VALUE)
                    .addComponent(txtNomeProduto))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        dpDadosProdutoLayout.setVerticalGroup(
            dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpDadosProdutoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProduto)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoCusto)
                    .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMargem)
                    .addComponent(txtMargem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoVenda)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnEditar.setBackground(new java.awt.Color(204, 204, 204));
        btnEditar.setText("Editar");

        btnFechar.setBackground(new java.awt.Color(204, 204, 204));
        btnFechar.setText("Fechar");

        btnVisualizar.setBackground(new java.awt.Color(204, 204, 204));
        btnVisualizar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnVisualizar.setText("Visualizar histórico de preços");

        dpPrincipal.setLayer(dpDadosProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPrincipal.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPrincipal.setLayer(btnFechar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPrincipal.setLayer(btnVisualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpPrincipalLayout = new javax.swing.GroupLayout(dpPrincipal);
        dpPrincipal.setLayout(dpPrincipalLayout);
        dpPrincipalLayout.setHorizontalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(dpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpPrincipalLayout.createSequentialGroup()
                        .addComponent(dpDadosProduto)
                        .addContainerGap(10, Short.MAX_VALUE))
                    .addGroup(dpPrincipalLayout.createSequentialGroup()
                        .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        dpPrincipalLayout.setVerticalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPrincipalLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(dpDadosProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JDesktopPane dpDadosProduto;
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblMargem;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPrecoCusto;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JTextField txtMargem;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPrecoCusto;
    private javax.swing.JTextField txtPrecoVenda;
    // End of variables declaration//GEN-END:variables

    // getters
    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnVisualizar() {
        return btnVisualizar;
    }

    public JComboBox<String> getCbCategoria() {
        return cbCategoria;
    }

    public JDesktopPane getDpDadosProduto() {
        return dpDadosProduto;
    }

    public JDesktopPane getDpPrincipal() {
        return dpPrincipal;
    }

    public JLabel getLblCategoria() {
        return lblCategoria;
    }

    public JLabel getLblMargem() {
        return lblMargem;
    }

    public JLabel getLblNomeProduto() {
        return lblNomeProduto;
    }

    public JLabel getLblPrecoCusto() {
        return lblPrecoCusto;
    }

    public JLabel getLblPrecoVenda() {
        return lblPrecoVenda;
    }

    public JTextField getTxtMargem() {
        return txtMargem;
    }

    public JTextField getTxtNomeProduto() {
        return txtNomeProduto;
    }

    public JTextField getTxtPrecoCusto() {
        return txtPrecoCusto;
    }

    public JTextField getTxtPrecoVenda() {
        return txtPrecoVenda;
    }
}
